#!/usr/bin/env bash
# Rebuilds profile/README.md so the organisation profile says what
# lwplugins.com says: the same packages from lwplugins/registry, in the same
# order (stable first), with the facts read from where the site reads them —
# the latest release tag, the plugin header and the docs page.
#
# Run from the repository root. Needs curl, jq and an authenticated gh.
set -euo pipefail

REGISTRY_URL="https://raw.githubusercontent.com/lwplugins/registry/main/plugins.json"
DOCS_URL="https://docs.lwplugins.com/en/plugins"
OUT="profile/README.md"

registry=$(curl -sf "$REGISTRY_URL") || { echo "Failed to fetch registry" >&2; exit 1; }

badge() {
  case "$1" in
    stable) echo '![stable](https://img.shields.io/badge/-stable-07875C)' ;;
    alpha)  echo '![alpha](https://img.shields.io/badge/-alpha-C22B2B)' ;;
    *)      echo '![beta](https://img.shields.io/badge/-beta-A66A00)' ;;
  esac
}

# "Requires PHP: 8.2" / " * Version: 1.5.1" out of a plugin header.
header_field() {
  printf '%s' "$1" | grep -m1 -iE "^[[:space:]*]*$2:" | sed 's/^[^:]*:[[:space:]]*//' | tr -d '\r' || true
}

rows=""
count=0
while IFS=$'\t' read -r slug name desc status icon; do
  header=$(curl -sf "https://raw.githubusercontent.com/lwplugins/$slug/main/$slug.php" || true)

  # The release is what people can install; the header is only a fallback.
  version=$(gh release view -R "lwplugins/$slug" --json tagName -q .tagName 2>/dev/null || true)
  version=${version#v}
  [ -n "$version" ] || version=$(header_field "$header" "Version")

  php=$(header_field "$header" "Requires PHP")
  php_cell="—"
  [ -n "$php" ] && php_cell="$php+"

  # A docs column entry only where a page actually exists.
  code=$(curl -s -o /dev/null -w '%{http_code}' "$DOCS_URL/$slug" || true)
  docs="—"
  [ "$code" = "200" ] && docs="[Docs]($DOCS_URL/$slug)"

  rows+="| <img src=\"$icon\" width=\"20\" height=\"20\" alt=\"\"> | [$name](https://github.com/lwplugins/$slug) | $desc | $(badge "$status") | ${version:-—} | $php_cell | $docs |"$'\n'
  count=$((count + 1))
done < <(printf '%s' "$registry" | jq -r '
  {stable: 0, beta: 1, alpha: 2} as $rank
  | to_entries
  | sort_by([($rank[.value.status // "beta"] // 1), .value.name])[]
  | [ .key,
      .value.name,
      (.value.description | gsub("\\|"; "\\|")),
      (.value.status // "beta"),
      (.value.icon_svg // "https://raw.githubusercontent.com/lwplugins/registry/main/icons/\(.key).svg") ]
  | @tsv')

{
cat <<'MD'
<!-- Generated by .github/scripts/generate-readme.sh from lwplugins/registry.
     Edit the script, not this file — the next run overwrites it. -->

# LW Plugins

**Zero bloat. Pure performance.**

Standalone WordPress plugins for developers who read the source. No tracking, no license keys, no upsell screens. Install what you need with Composer, and nothing else comes along with it.

[lwplugins.com](https://lwplugins.com) · [Documentation](https://docs.lwplugins.com) · [Manifesto](https://lwplugins.com/about/) · [Packagist](https://packagist.org/packages/lwplugins/)

MD

printf '## %s independent packages\n\n' "$count"

cat <<'MD'
Each one ships alone. No shared framework to install, no cross-dependencies to untangle — remove any of them and the rest keep working exactly as before.

| | Package | Description | Status | Version | PHP | Docs |
|---|---|---|---|---|---|---|
MD

printf '%s' "$rows"

cat <<'MD'

Every package installs the same way:

```bash
composer require lwplugins/<package>
wp plugin activate <package>
```

All LW packages share one **LW Plugins** admin menu, no matter how many you install.

Prefer a ZIP? Take it from the package's **Releases** page, not the green *Code → Download ZIP* button — that one gives you the whole repository under a folder name WordPress will not recognise as the same plugin on update.

## What lightweight means here

- **No bloat** — no onboarding wizards, no upsell screens, no dashboard widgets you did not ask for. The settings page is a form.
- **No telemetry** — no tracking, no phone-home license checks, no analytics beacons. Nothing leaves the site unless you wire it up yourself.
- **Modular** — every package stands alone. They share one admin menu when installed together, and nothing else.
- **Readable** — strict types, PSR-4 autoloading, WordPress Coding Standards, PHPStan level 5. Small enough to audit before you install it.

## Contributing

Every package ships its own `readme.txt`, `CHANGELOG.md` and hook reference. Issues and pull requests go to the package's repository — there is no support portal, no ticket queue and no paid tier behind it.

## Sponsor

<a href="https://sinann.io/"><img src="https://sinann.io/favicon.svg" alt="Sinann" width="40"></a>

Supported by [Sinann](https://sinann.io/).

## License

Open source under GPL-2.0-or-later.
MD
} > "$OUT"

echo "Wrote $OUT with $count packages"
